<?php

namespace App\Filament\Resources\EventResource\Pages;

use App\Filament\Resources\EventResource;
use App\Models\Event;
use App\Models\Room;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditEvent extends EditRecord
{
    protected static string $resource = EventResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()
                ->hidden(auth()->user()->is_blocked),
        ];
    }

    protected function getSaveFormAction(): Action
    {
        return parent::getSaveFormAction()
            ->hidden(auth()->user()->is_blocked); // TODO: Change the autogenerated stub
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        if (Event::isConflict($data)) {
            $roomName = Room::find($data['room_id'])->name;

            Notification::make('cantBook')
                ->title('該時段 '.$roomName.' 已有預約')
                ->danger()
                ->send();

            $this->halt();
        }

        $record->update($data);

        return $record;
    }
}
